name: Deploy Build and Exported Files

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build with Next.js (No need to run export explicitly)
      - name: Build with Next.js
        run: npm run build

      # Step 5: Clone Target Repository
      - name: Clone Target Repository
        run: |
          git clone https://github.com/acm-ucsc/acm-web-ucsc.io.git target-repo
          rm -rf target-repo/*
        env:
          GIT_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      # Step 6: Copy Build Files to Target Repository
      - name: Copy Build Files
        run: |
          cp -r dist/* target-repo/

      # Step 7: Deploy to Target Repository
      - name: Deploy to Target Repository
        run: |
          cd target-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy build files from source repository"
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/acm-ucsc/acm-web-ucsc.io.git

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          publish_branch: gh-pages
          publish_dir: ./dist  # Use the correct directory where static files are located
